---
logging:
  level: INFO
  loggers:
    com.gitlab.rurouniwallace.notes: DEBUG

upstreamTenacity:
  health:
    executionIsolationThreadTimeoutInMillis: 2000
    threadpool:
      threadPoolCoreSize: 10

swagger:
  resourcePackage: com.gitlab.rurouniwallace.notes.resources